build:
  image: quay.io/singularity/singularity:v3.4.0-slim
  script:
      - singularity build Singularity.sif Singularity
  
  # This is where you can save job artifacts
  # https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html
  # You can specify the path to containers or the build folder to save.
  # Don't forget to save your recipes too!
  artifacts:
      paths:
        - build/Singularity.sif
        - build/Singularity
