
variables:
  RECIPE: Singularity
  SINGULARITY_IMAGE: singularity.sif
  DEPOSITION: 4332268
    
build:
  image: 
    name: quay.io/tpall/singularity-curl-jq
    entrypoint: [""]
  before_script:
    - chmod +x .gitlabci/upload.sh
  script:
    - singularity build --notest $SINGULARITY_IMAGE $RECIPE
    - /bin/sh .gitlabci/upload.sh $DEPOSITION $SINGULARITY_IMAGE
    - /bin/sh .gitlabci/upload.sh $DEPOSITION $RECIPE
