image: 
  name: quay.io/singularity/singularity:v3.4.0-slim
  entrypoint: [""]

build:
  variables:
    DEPOSITION: 4332268
  script:
    - singularity build --notest Singularity.sif Singularity
    - ./zenodo_upload.sh $DEPOSITION Singularity.sif
    - ./zenodo_upload.sh $DEPOSITION Singularity
