name: geo-htseq-paper-env
channels:
  - bioconda
  - conda-forge
  - r
  - dorbarker
dependencies:
  - r-dplyr
  - r-readr
  - r-purrr
  - r-stringr
  - r-tidyr
  - r-lubridate
  - r-here
  - r-staplr
  - r-rmarkdown>= 2.5
  - r-bookdown
  - r-rticles=0.17

