name: Singularity Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config

    - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.2.1
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
        tar xzv && \
        cd singularity && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install
        rm -rf .singularity/
    
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Pull Container
      run: |
       singularity pull --name container.sif shub://tpall/geo-htseq-paper

    - name: Test Container
      run: |
       singularity exec container.sif Rscript -e 'library("rstan"); example(stan_model, package = "rstan", run.dontrun = TRUE)'
