name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Snakemake environment
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda install -c conda-forge -q mamba
          mamba env create -q --name snakemake --file test-environment.yml

      - name: Setup apt dependencies
        run: |
          sudo apt install -y stress \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            wget \
            pkg-config \
            git \
            cryptsetup

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'

      - name: Setup singularity
        run: |
          export VERSION=3.6.2
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
          tar -xzf singularity-${VERSION}.tar.gz
          cd singularity
          ./mconfig
          make -C builddir
          sudo make -C builddir install

      - name: Test run
        env:
          CI: true
        run: |
          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate snakemake

          snakemake --use-conda --use-singularity --restart-times 0 -j

